#Minecraft server properties
#Sat Apr 16 12:28:43 MST 2022
view-distance=10
max-build-height=256
server-ip=
level-seed=
allow-nether=false
gamemode=0
enable-command-block=false
server-port=25565
enable-rcon=false
server-name=
enable-query=false
op-permission-level=4
generator-settings=
resource-pack=
player-idle-timeout=0
level-name=world
motd=
announce-player-achievements=false
force-gamemode=false
debug=false
hardcore=false
white-list=false
broadcast-console-to-ops=true
pvp=true
spawn-npcs=true
spawn-animals=true
generate-structures=true
snooper-enabled=true
difficulty=1
I\#Minecraft=server properties
network-compression-threshold=256
level-type=DEFAULT
spawn-monsters=false
max-players=2020
spawn-protection=0
online-mode=false
allow-flight=false
resource-pack-hash=
max-world-size=29999984
